# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
                ('plannedby', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='Vactions', to='User.User')),
            ],
        ),
    ]
