# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20180129_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vacations', to='User.User')),
                ('users', models.ManyToManyField(to='User.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='vaction',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='vaction',
            name='users',
        ),
        migrations.DeleteModel(
            name='Vaction',
        ),
    ]
