# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dojo_Ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='dojo_id',
        ),
    ]
